// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://getvlmzpzgiihhslhcvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldHZsbXpwemdpaWhoc2xoY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNTY2NTQsImV4cCI6MjA3NjczMjY1NH0.F9yycJH5e7Urd0MgXd3ZdeudKZutaiznTTsw6dZ2nlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});